version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/gh-cmcm/
archives:
  - name_template: '{{ .Os }}-{{ .Arch }}'
    format: binary
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  disable: true
