name: test
on:
  push:
    branches:
      - "**"
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x
      - name: checkout
        uses: actions/checkout@v3
      - name: test
        run: go test -cover -race ./...